import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { MainPage } from "./components/todoPage";
import { TodoList } from "./components/todoList";
import { NextPage } from "next";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });
export type TaskType = {
  id: number;
  text: string;
  completed: boolean;
};

export const Home: NextPage = () => {
  const [taskList, setTaskList] = useState<TaskType[]>([]);
  return (
    <div>
      <Head>
        <title>React Todo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.body}>
        <MainPage taskList={taskList} setTaskList={setTaskList} />
        <TodoList taskList={taskList} setTaskList={setTaskList} />
      </main>
    </div>
  );
};
export default Home;
